blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostUpdateView, BlogPostListView, BlogPostDetailView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
                  path('create-post/', BlogPostCreateView.as_view(), name='blogpost_create'),
                  path('post-update/<slug>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
                  path('post-list/', BlogPostListView.as_view(), name='blogpost_list'),
                  path('post-detail/<slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
                  path('post-delete/<slug>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from Catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls', namespace='shop')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/<int:id>/', cache_page(60 * 15)(views.ProductDetailView.as_view()), name='product_detail'),
]

blog/models.py
from autoslug import AutoSlugField
from django.db import models

from user.models import User


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок поста")
    slug = AutoSlugField(populate_from='title', unique=True, verbose_name="Ссылка на пост")
    content = models.TextField(verbose_name="Текст поста")
    preview_image = models.ImageField(upload_to="blog_preview", verbose_name="Превью поста", null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=False, verbose_name="Опубликованные посты")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogposts', verbose_name='Создатель',
                              blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-created_at']

blog/forms.py
from blog.models import BlogPost
from django.forms import ModelForm, forms


class BlogPostForm(ModelForm):
    banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

    class Meta:
        model = BlogPost
        fields = ("title", "content", "preview_image", "is_published")

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title in self.banned_words:
            raise forms.ValidationError("Используемые слова недопустимы")
        return title

    def clean_content(self):
        content = self.cleaned_data["content"]
        if content in self.banned_words:
            raise forms.ValidationError("Используемые слова недопустимы")
        return content

blog/views.py
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.forms import BlogPostForm
from blog.models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blogpost_list.html'
    context_object_name = 'blogposts'
    paginate_by = 10

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blogpost_detail.html'
    context_object_name = 'blogpost'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogPostCreateView(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'blogpost_form.html'
    success_url = reverse_lazy('blog:blogpost_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blogpost_detail', kwargs={'slug': self.object.slug})


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'blogpost_form.html'
    context_object_name = 'blogposts'
    success_url = reverse_lazy('blog:blogpost_list')

    def get_success_url(self):
        return reverse('blog:blogpost_detail', kwargs={'slug': self.object.slug})

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not self.request.user == obj.owner and not self.request.user.is_superuser:
            raise PermissionDenied("Недостаточно прав.")
        return obj

    def get_form_class(self):
        user = self.request.user
        if self.object.owner == user or user.is_superuser or user.has_perms([
            "shop.can_cancel_publication",
            "shop.can_change_description_any",
            "shop.can_change_category_any"
        ]):
            return BlogPostForm
        else:
            raise PermissionDenied("Недостаточно прав.")


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'blogpost_confirm_delete.html'
    success_url = reverse_lazy('blog:blogpost_list')

blog/templates/blogpost_confirm_delete.html
{% extends 'product/base.html' %}

<title>{% block title %} Подтвердите удаление поста | eLectronic {% endblock %}</title>
{% block content %}
    <h1>Удаление поста</h1>
    <p>Вы уверены, что хотите удалить пост "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
        <a href="{% url 'blog:blogpost_detail' object.slug %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}
{% block product_actions %}
{% endblock %}

blog/templates/blogpost_detail.html
{% extends 'product/base.html' %}

<title>{% block title %}Блог | eLectronic{% endblock %}</title>
{% block content %}
    <div class="col">
        <h1>{{ blogpost.title }}</h1>
        {% if blogpost.preview_image %}
        <img src="{{ blogpost.preview_image.url }}" class="img-fluid mb-3" alt="{{ blogpost.title }}">
        {% endif %}
            <p>Текст: {{ blogpost.content }}</p>
            <p>Создано: {{ blogpost.created_at }}</p>
            <p>Просмотров: {{ blogpost.views_count }}</p>
            <p>Опубликовано: {% if blogpost.is_published %}Да{% else %}Нет{% endif %}</p>
            <a href="{% url 'blog:blogpost_update' blogpost.slug %}" class="btn btn-warning">Редактировать</a>
            <a href="{% url 'blog:blogpost_delete' blogpost.slug %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'blog:blogpost_list' %}" class="btn btn-primary">Назад</a>

    </div>
{% endblock %}
{% block product_actions %}
{% endblock %}

blog/templates/blogpost_form.html
{% extends 'product/base.html' %}

<title>{% block title %}Блог | eLectronic{% endblock %}</title>
{% block content %}
<div class="container my-5">
    <h1>{% if object %}Редактировать пост{% else %}Создать пост{% endif %}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if not object %}
        <button type="submit" class="btn btn-success">Создать</button>
        {% else %}
        <button type="submit" class="btn btn-success">Сохранить</button>
        {% endif %}
    </form>
    {% endblock %}
    {% block product_actions %}
    {% endblock %}

blog/templates/blogpost_list.html
{% extends 'product/base.html' %}

<title>{% block title %} Блог | eLectronic {% endblock %}</title>

{% block nav_link %}
<div class="text-center">
    <h1 class="fw-light">Блог</h1>
    <p class="lead text-body-secondary">eLectronic</p>
    <a class="btn btn-success mt-3" href="{% url 'blog:blogpost_create' %}" role="button">Создать пост</a>
</div>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if object_list %}
            {% for blogpost in object_list %}
            {% if blogpost.is_published %}
            <div class="col-md-4">
                <div class="card" style="width: 300px;">
                    {% if blogpost.preview_image %}
                    <img src="{{ blogpost.preview_image.url }}" class="card-img-top">
                    {% else %}
                    <img src="https://georgpolymer.ru/local/templates/main/img/noImg.jpg" height="300"
                         class="card-img-top"
                         style="max-width: 300px;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ blogpost.title }}</h5>
                        <p class="card-text">{{ blogpost.content|truncatewords:20 }}</p>
                        <p>Просмотров: {{ blogpost.views_count }}</p>
                        <a href="{% url 'blog:blogpost_detail' blogpost.slug %}"
                           class="btn btn-sm btn-primary">Читать далее...</a>
                        <small class="text-body-secondary">{{ blogpost.created_at|timesince }}</small>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="text-center" style="font-size: 1.5rem; font-weight: bold;">
                Постов пока нет :(
            </div>
            {% endif %}
        </div>
    </div>


    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for i in paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    {% endblock %}
</div>