Catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from Catalog.apps import CatalogConfig
from Catalog.views import ProductListView, ProductDetailView, ProductCreateView, HomeView, ProductUpdateView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path('base/', ProductListView.as_view(), name='product_list'),
                  path('product/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
                  path('product/create/', ProductCreateView.as_view(), name='product_create'),
                  path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
                  path('categories/', CategoryListView.as_view(), name='category_list'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostUpdateView, BlogPostListView, BlogPostDetailView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
                  path('create-post/', BlogPostCreateView.as_view(), name='blogpost_create'),
                  path('post-update/<slug>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
                  path('post-list/', BlogPostListView.as_view(), name='blogpost_list'),
                  path('post-detail/<slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
                  path('post-delete/<slug>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from Catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls', namespace='shop')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/<int:id>/', cache_page(60 * 15)(views.ProductDetailView.as_view()), name='product_detail'),
]

Catalog/models.py
from django.db import models
from user.models import User


class Category(models.Model):
    name = models.CharField(verbose_name='Наименование категории', help_text="Введите наименование категории",
                            blank=True, null=True)
    description = models.TextField(verbose_name='Описание категории', help_text="Введите описание категории",
                                   blank=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name='Наименование', help_text="Введите наименование")
    description = models.TextField(verbose_name='Описание', help_text="Введите описание")
    picture = models.ImageField(verbose_name='Изображение',blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория',
                                 help_text="Введите категорию",
                                 null=True, blank=True, related_name="products")
    price = models.CharField(verbose_name='Цена', help_text="Введите цену")
    create_at = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Дата создания',
                                     help_text="Введите дату создания")
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Дата последнего изменения',
                                      help_text="Введите дату создания последнего изменения")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products', verbose_name='Создатель',
                              blank=True, null=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name', 'description', 'category', 'price', 'create_at', 'updated_at']
        permissions = [
            ("can_cancel_publication", "Может отменять публикацию продукта"),
            ("can_change_description_any", "Может менять описание любого продукта"),
            ("can_change_category_any", "Может менять категорию любого продукта"),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions')
    version_number = models.CharField(max_length=20)
    version_name = models.CharField(max_length=255)
    is_current = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Версия товара"
        verbose_name_plural = "Версии товара"

    def __str__(self):
        return f"{self.version_name} ({self.version_number})"

Catalog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django.forms import ModelForm
from Catalog.models import Product, Version


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ("views_counter", "is_published", "owner")


class ProductModerateForm(ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category", "is_published")


class VersionFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('product', css_class='form-control'),
            Field('version_number', css_class='form-control'),
            Field('version_name', css_class='form-control'),
            Field('is_current', css_class='form-check-input'),
            Submit('submit', 'Save', css_class='btn btn-primary')
        )


class VersionForm(ModelForm, VersionFormMixin):
    class Meta:
        model = Version
        fields = "__all__"

Catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView
from django.views.generic import ListView
from .services import get_cached_categories
from Catalog.forms import ProductForm, VersionForm
from Catalog.models import Product, Version


class HomeView(ListView):
    model = Product
    template_name = 'product/home.html'
    context_object_name = 'latest_products'
    order_by = '-create_at'
    queryset = Product.objects.order_by('-create_at')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        latest_products = self.object_list

        for product in latest_products:
            print(f"Название: {product.name}")
            print(f"Описание: {product.description}")
            print(f"Цена: {product.price}")
            print(f"Дата создания: {product.create_at}")
            print()

        return context


class CategoryListView(ListView):
    template_name = 'category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return get_cached_categories()


class ProductListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user:login')
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context["products"]

        for product in products:
            current_version = product.versions.filter(is_current=True).first()
            if current_version:
                product.current_version = {
                    "version_number": current_version.version_number,
                    "version_name": current_version.version_name,
                }
            else:
                product.current_version = None

        return context

    def get_queryset(self):
        return get_cached_categories()


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'product/product_details.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'product/product_form.html'
    form_class = ProductForm
    success_url = reverse_lazy('shop:product_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_form.html'
    success_url = reverse_lazy('shop:product_details')

    def get_success_url(self):
        return reverse("shop:product_details", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_fromset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = version_fromset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = version_fromset(instance=self.object)
        return context_data

    def get_form_class(self):
        user = self.request.user
        if self.object.owner == user or user.is_superuser or user.has_perms(["shop.can_cancel_publication",
                                                                             "shop.can_change_description_any",
                                                                             "shop.can_change_category_any"]):
            return ProductForm
        raise PermissionDenied

Catalog/templates/product/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static '/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}eLectronic{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="{% static '/img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static '/img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% static '/img/favicons/manifest.json' %}">
    <link rel="mask-icon" href="{% static '/img/favicons/safari-pinned-tab.svg' %}" color="#712cf9">
    <link rel="icon" href="{% static '/img/favicons/favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
{% include 'product/includes/inc_menu.html' %}
</header>

<main>
    {% block product_actions %}
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    {% block nav_link %}
                        <h1 class="fw-light">Магазин электроники</h1>
                        <p class="lead text-body-secondary">eLectronic</p>
                        <p>
                            <a href="{% url 'shop:product_create' %}" class="btn btn-primary my-2">Добавление товара</a>
                        </p>
                    {% endblock %}
                </div>
            </div>
        </section>
    {% endblock %}

    {% block content %}
    {% endblock %}

</main>

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                eLectronic Shop
                <small class="d-block mb-3 text-muted">&copy; {% now "Y" %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'shop:product_list' %}">Товары</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:blogpost_list' %}">Блог</a></li>
                    <li><a class="text-muted" href="{% url 'blog:blogpost_create' %}">Создать пост</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

Catalog/templates/product/blogpost_detail.html
{% extends 'product/base.html' %}

<title>{% block title %}Блог | eLectronic{% endblock %}</title>
{% block content %}
    <div class="col">
        <h1>{{ blogpost.title }}</h1>
        {% if blogpost.preview_image %}
        <img src="{{ blogpost.preview_image.url }}" class="img-fluid mb-3" alt="{{ blogpost.title }}">
        {% endif %}
            <p>Текст: {{ blogpost.content }}</p>
            <p>Создано: {{ blogpost.created_at }}</p>
            <p>Просмотров: {{ blogpost.views_count }}</p>
            <p>Опубликовано: {% if blogpost.is_published %}Да{% else %}Нет{% endif %}</p>
            <a href="{% url 'shop:blogpost_update' blogpost.slug %}" class="btn btn-warning">Редактировать</a>
            <a href="{% url 'shop:blogpost_delete' blogpost.slug %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'shop:blogpost_list' %}" class="btn btn-primary">Назад</a>
    </div>
{% endblock %}
{% block product_actions %}
{% endblock %}

Catalog/templates/product/blogpost_list.html
{% extends 'product/base.html' %}

<title>{% block title %} Блог | eLectronic {% endblock %}</title>

{% block nav_link %}
<div class="text-center">
    <h1 class="fw-light">Блог</h1>
    <p class="lead text-body-secondary">eLectronic</p>
    <a class="btn btn-success mt-3" href="{% url 'shop:blogpost_create' %}" role="button">Создать пост</a>
</div>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if object_list %}
            {% for blogpost in object_list %}
            {% if blogpost.is_published %}
            <div class="col-md-4">
                <div class="card" style="width: 300px;">
                    {% if blogpost.preview_image %}
                    <img src="{{ blogpost.preview_image.url }}" class="card-img-top">
                    {% else %}
                    <img src="https://georgpolymer.ru/local/templates/main/img/noImg.jpg" height="300"
                         class="card-img-top"
                         style="max-width: 300px;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ blogpost.title }}</h5>
                        <p class="card-text">{{ blogpost.content|truncatewords:20 }}</p>
                        <p>Просмотров: {{ blogpost.views_count }}</p>
                        <a href="{% url 'shop:blogpost_detail' blogpost.slug %}"
                           class="btn btn-sm btn-primary">Читать далее...</a>
                        <small class="text-body-secondary">{{ blogpost.created_at|timesince }}</small>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="text-center" style="font-size: 1.5rem; font-weight: bold;">
                Постов пока нет :(
            </div>
            {% endif %}
        </div>
    </div>


    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for i in paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    {% endblock %}
</div>

Catalog/templates/product/category_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Category List</title>
</head>
<body>
    <h1>Category List</h1>
    <ul>
        {% for category in categories %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Catalog/templates/product/confirm_delete_blogpost.html
{% extends 'product/base.html' %}

<title>{% block title %} Подтвердите удаление поста | eLectronic {% endblock %}</title>
{% block content %}
    <h1>Удаление поста</h1>
    <p>Вы уверены, что хотите удалить пост "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
        <a href="{% url 'shop:blogpost_detail' object.slug %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}
{% block product_actions %}
{% endblock %}

Catalog/templates/product/create_product.html
{% extends 'product/base.html' %}
{% block nav_link %}
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <section class="py-5 text-center container" >
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Создание нового товара</h1>
                    <p class="lead text-body-secondary">Магазин электроники | eLectronic</p>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button type="submit" class="btn btn-primary my-2">Добавить</button>
                    </p>
                </div>
            </div>
        </section>
    </form>
{% endblock %}
{#{% block product_actions %}#}
{#{% endblock %}#}

Catalog/templates/product/home.html
{% extends 'product/base.html' %}
{% load my_tags %}
{% block content %}
    <title>{% block title %} Главная | eLectronic {% endblock %}</title>

{% block nav_link %}
{% endblock %}
<body>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Добро пожаловать!</h1>
        <p class="lead">Вас приветствует сайт интернет-магазина электроники eLectronic!</p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
{% endblock %}

Catalog/templates/product/product_form.html
{% extends 'product/base.html' %}
{% block nav_link %}
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">{% if form.instance.pk %}Редактирование товара{% else %}Создание нового
                        товара{% endif %} </h1>
                    <p class="lead text-body-secondary">Магазин электроники | eLectronic</p>
                    {% csrf_token %}
                    {{ form.as_p }}

                {% if formset.forms is not empty %}
                <h3>Версии</h3>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% endfor %}
                {% endif %}

                    <p>
                        <button type="submit" class="btn btn-primary my-2">Добавить</button>
                    </p>
                </div>
            </div>
        </section>
    </form>
{% endblock %}

Catalog/templates/product/product_list.html
{% extends 'product/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for item in object_list %}
                    {% if item.is_published %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img height="250px" src="{{ item.picture | media_filter }}">
                            <div class="card-body">
                                <p class="card-text">{{ item.name }}</p>
                                {% if item.current_version %}
                                    <p>Текущая версия: {{ item.current_version.version_name }}
                                        ({{ item.current_version.version_number }})</p>
                                {% else %}
                                    <p>Текущая версия не указана</p>
                                {% endif %}
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-primary" href="{% url 'shop:product_details' item.pk %}"
                                           role="button">Подробнее</a>
                                            <a class="btn btn-secondary"
                                               href="{% url 'shop:product_update' item.pk %}" role="button">Редактировать</a>
                                    </div>
                                    <small class="text-body-secondary">{{ item.create_at }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}