blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostUpdateView, BlogPostListView, BlogPostDetailView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
                  path('create-post/', BlogPostCreateView.as_view(), name='blogpost_create'),
                  path('post-update/<slug>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
                  path('post-list/', BlogPostListView.as_view(), name='blogpost_list'),
                  path('post-detail/<slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
                  path('post-delete/<slug>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from Catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls', namespace='shop')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/<int:id>/', cache_page(60 * 15)(views.ProductDetailView.as_view()), name='product_detail'),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .apps import UserConfig
from .views import UserRegisterView, PasswordResetView, email_confirm

app_name = UserConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
]

user/models.py
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='Email', unique=True, help_text="Введите Email")
    avatar = models.ImageField(verbose_name='avatar', blank=True, null=True, upload_to="users/avatars/")
    phone_number = models.CharField(verbose_name='Телефон', max_length=12, blank=True, null=True,
                                    help_text="Введите номер телефона")
    country = models.CharField(verbose_name='country', max_length=30, blank=True)

    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['email', 'phone_number', 'country']

    def __str__(self):
        return self.email

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm

from user.models import User


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=30)
    password1 = forms.CharField(required=True, max_length=30)
    password2 = forms.CharField(required=True, max_length=30)

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ResetUserPasswordForm(PasswordResetForm):
    email = forms.EmailField(required=True, max_length=30)

user/views.py
import random
import string
import secrets

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, FormView

from django.conf import settings
from user.forms import CreateUserForm, ResetUserPasswordForm
from user.models import User


class UserRegisterView(CreateView):
    template_name = 'user/user_form.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        verification_link = f'http://{host}/user/email_confirm/{token}/'
        subject = 'Подтверждение почты'
        from_email = settings.EMAIL_HOST_USER
        recipient_list = [user.email]
        send_mail(subject, verification_link, from_email, recipient_list)
        return super().form_valid(form)


def email_confirm(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse_lazy("user:login"))


class PasswordResetView(FormView):
    template_name = 'password_reset.html'
    form_class = ResetUserPasswordForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
            user.is_active = True
            new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
            user.password = make_password(new_password)
            user.save()

            subject = 'Сброс пароля.'
            message = f'Ваш новый пароль был сгенерирован автоматически:\n {new_password}'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [user.email]
            send_mail(subject, message, from_email, recipient_list)
        except User.DoesNotExist:
            form.add_error('email', 'Пользователь с таким адресом электронной почты не найден.')

        return super().form_valid(form)

user/templates/login.html
{% extends 'product/base.html' %}
{% block nav_link %}
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <section class="py-5 text-center container" >
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Авторизация</h1>
                    <p class="lead text-body-secondary">Магазин электроники | eLectronic</p>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button type="submit" class="btn btn-primary my-2">Войти</button>
                    <a href="{% url 'user:register' %}" class="btn btn-outline-secondary my-2">Регистрация</a>
                    </p>
                    <h4 class="fw-lighter">
                        <a>Забыли пароль?</a>
                    </h4>
                    <a href="{% url 'user:password_reset' %}" class="btn">Восстановить</a>
                </div>
            </div>
        </section>
    </form>
{% endblock %}

user/templates/password_reset.html
{% extends 'product/base.html' %}
{% block nav_link %}
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
    <section class="py-5 text-center container" >
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Восстановление пароля</h1>
                    <p class="lead text-body-secondary">Магазин электроники | eLectronic</p>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button type="submit" class="btn btn-primary my-2">Сбросить пароль</button>
                </div>
            </div>
        </section>
    </form>
{% endblock %}

user/templates/verificate_email.html
<body>
    <p>Здравствуйте, {{ user.email }}!</p>
    <p>Благодарим за регистрацию на нашем сервисе. Пожалуйста, перейдите по ссылке ниже для верификации аккаунта:</p>
    <p><a href="{{ verification_link }}">Verify Email</a></p>
    <p>Если вы не регистрировались на сайте 0.0.0.1:8000, пожалуйста, проигнорируйте это сообщение.</p>

</body>